### ISSUE TITLE
How to use / enable this plugin?

### ISSUE THREAD

**Issue by clehene** [OpenASR/idiolect#57]
There's no mention in the docs on how to actually enable / use the plugin. 

E.g. 
-------
# Using

Once you install the plugin you can start talking directly to it. 
Try "Tell me about yourself"
--------
I've installed the plugin, but I can't figure out how to use it.
Speaking voice commands directly doesn't seem to work.

**Comment by breandan** [comment]
Have you enabled the microphone? If you click on the "record" button in the toolbar, does it produce any output?

**Comment by clehene** [comment]
I don't see any record button. Here's my toolbar
<img width="492" alt="Screen Shot 2019-03-22 at 7 28 29 PM" src="https://user-images.githubusercontent.com/101597/54860536-c1d32d00-4cd8-11e9-84a0-1c8414476e61.png">

**Comment by clehene** [comment]
I noticed I'm getting this on startup. Perhaps that's why?

```
com.intellij.diagnostic.PluginException: com/johnlindquist/acejump/config/AceConfig [Plugin: com.jetbrains.idear]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:153)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:471)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:459)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActions(ActionManagerImpl.java:1266)
	at com.intellij.openapi.actionSystem.impl.ActionPreloader.preload(ActionPreloader.java:32)
	at com.intellij.openapi.application.Preloader.lambda$null$0(Preloader.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.application.Preloader.lambda$initComponent$1(Preloader.java:63)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:220)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.lambda$run$0(BoundedTaskExecutor.java:198)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:224)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: com/johnlindquist/acejump/config/AceConfig
	at org.openasr.idear.VoiceRecordControllerAction.<clinit>(VoiceRecordControllerAction.kt:12)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:146)
	... 19 more
Caused by: java.lang.ClassNotFoundException: com.johnlindquist.acejump.config.AceConfig PluginClassLoader[com.jetbrains.idear, 1.3.3] com.intellij.ide.plugins.cl.PluginClassLoader@335c01a7
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:51)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 23 more
```

**Comment by BK-Choi** [comment]
i can't use it and the same error message, and don't know what to do.
anyone of OpenASR, could you give us any visible examples?

- [x] add idear buttons on toolbar manually
- [x] add keymap for idear functions

```
kotlin.KotlinNullPointerException
	at org.openasr.idear.actions.ExecuteActionFromPredefinedText.actionPerformed(ExecuteActionFromPredefinedText.kt:10)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:261)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:278)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:183)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:147)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:415)
	at java.awt.Component.processEvent(Component.java:6315)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:741)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:686)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by breandan** [comment]
Can you try [manually installing](https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk) the [latest development build](https://teamcity.jetbrains.com/repository/download/idear_buildplugin/2160493:id/idear-1.3.4.zip) and report if this is still an issue?

**Comment by obasilakis** [comment]
Hey @breandan, I just tried manually installing and the error persists. Stacktrace.txt is identical to the one @clehene posted, any hints?

**Comment by breandan** [comment]
Hi folks, apologies for the delayed response. Long story short, we recently rewrote Idear from scratch using the [Vosk speech recognizer](https://alphacephei.com/vosk/) and published a [new plugin](https://plugins.jetbrains.com/plugin/20776-idiolect) along with some example commands in [the docs](https://github.com/OpenASR/idiolect/blob/master/docs/example-phrases.md). It now supports defining custom commands by creating a file with [IDE action bindings](https://github.com/OpenASR/idiolect/blob/master/src/main/resources/phrases.example.properties). If you get the chance to try it out, @nalbion and I would appreciate reading your feedback. Thanks for your patience!
